-- 코드를 입력하세요
SELECT ORDERS.FLAVOR
FROM FIRST_HALF ORDERS
INNER JOIN ICECREAM_INFO INFO ON ( ORDERS.FLAVOR = INFO.FLAVOR )
WHERE ORDERS.TOTAL_ORDER >= 3000
AND INFO.INGREDIENT_TYPE = "fruit_based"
ORDER BY ORDERS.TOTAL_ORDER DESC